name: dbt_snowflake_analytics
version: "1.0.0"
config-version: 2
profile: dbt_snowflake_analytics

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  dbt_snowflake_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

seeds:
  dbt_snowflake_analytics:
    +schema: raw
